import {
  BadgeCheck,
  BookOpen,
  CalendarClock,
  Clapperboard,
  ClipboardCheck,
  Globe,
  Handshake,
  Heart,
  Lock,
  Megaphone,
  MessageSquare,
  Mic,
  Newspaper,
  Radio,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  UserPlus,
  UserRound,
  Users,
  type LucideIcon,
} from "lucide-react";

/** Central icon lookup so section content stays data-driven. */
export const iconMap: Record<string, LucideIcon> = {
  "badge-check": BadgeCheck,
  "book-open": BookOpen,
  "calendar-clock": CalendarClock,
  clapperboard: Clapperboard,
  "clipboard-check": ClipboardCheck,
  globe: Globe,
  handshake: Handshake,
  heart: Heart,
  lock: Lock,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  mic: Mic,
  newspaper: Newspaper,
  radio: Radio,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  "trending-up": TrendingUp,
  "user-plus": UserPlus,
  "user-round": UserRound,
  users: Users,
};
